import type { AgentDefinition, GeneratedFile, HarnessGenerator } from "./types.js";
import type { WitboostConfig } from "../config/schema.js";
import { buildSkillsSection, resolveVariables } from "./shared.js";

const RUN_SH = `#!/bin/sh
# Auto-generated by witboost-ai-toolkit setup — do not edit manually
# Finds node from nvm, fnm, volta, homebrew, or PATH, then starts the MCP server.
# Using this wrapper avoids "spawn node ENOENT" errors in GUI apps (VS Code,
# Cursor, etc.) that launch processes without inheriting the shell PATH.

# ── nvm (no shell sourcing needed) ────────────────────────────────────
_NVM_DIR="\${NVM_DIR:-\$HOME/.nvm}"
if [ -d "\$_NVM_DIR/versions/node" ]; then
  # 1. Honour the default alias (resolves chains like lts/* -> lts/iron -> vX.Y.Z)
  _NVM_ALIAS_FILE="\$_NVM_DIR/alias/default"
  if [ -f "\$_NVM_ALIAS_FILE" ]; then
    _NVM_ALIAS="\$(cat "\$_NVM_ALIAS_FILE")"
    # Follow alias chains up to 4 levels deep
    for _i in 1 2 3 4; do
      _CHAIN="\$_NVM_DIR/alias/\$_NVM_ALIAS"
      [ -f "\$_CHAIN" ] || break
      _NVM_ALIAS="\$(cat "\$_CHAIN")"
    done
    _NODE="\$_NVM_DIR/versions/node/\$_NVM_ALIAS/bin/node"
    [ -x "\$_NODE" ] && NODE_BIN="\$_NODE"
  fi
  # 2. Fall back to the latest installed version
  if [ -z "\$NODE_BIN" ]; then
    _NODE="\$(ls -1d "\$_NVM_DIR/versions/node"/*/bin/node 2>/dev/null | sort -V | tail -1)"
    [ -x "\$_NODE" ] && NODE_BIN="\$_NODE"
  fi
fi

# ── fnm ───────────────────────────────────────────────────────────────
if [ -z "\$NODE_BIN" ]; then
  _FNM_DIR="\${FNM_DIR:-\$HOME/.local/share/fnm}"
  _NODE="\$(ls -1d "\$_FNM_DIR/node-versions"/*/installation/bin/node 2>/dev/null | sort -V | tail -1)"
  [ -x "\$_NODE" ] && NODE_BIN="\$_NODE"
fi

# ── volta ─────────────────────────────────────────────────────────────
if [ -z "\$NODE_BIN" ] && [ -x "\$HOME/.volta/bin/node" ]; then
  NODE_BIN="\$HOME/.volta/bin/node"
fi

# ── homebrew (Apple Silicon / Intel) ─────────────────────────────────
if [ -z "\$NODE_BIN" ] && [ -x "/opt/homebrew/bin/node" ]; then
  NODE_BIN="/opt/homebrew/bin/node"
fi
if [ -z "\$NODE_BIN" ] && [ -x "/usr/local/bin/node" ]; then
  NODE_BIN="/usr/local/bin/node"
fi

# ── system PATH ───────────────────────────────────────────────────────
if [ -z "\$NODE_BIN" ] && command -v node >/dev/null 2>&1; then
  NODE_BIN="\$(command -v node)"
fi

if [ -z "\$NODE_BIN" ]; then
  echo "witboost-ai-toolkit: node not found. Install Node.js >= 18 via nvm, volta, or homebrew." >&2
  exit 1
fi

SCRIPT_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
exec "\$NODE_BIN" "\$SCRIPT_DIR/dist/index.cjs" "\$@"
`;

const RUN_CMD = `@echo off
:: Auto-generated by witboost-ai-toolkit setup — do not edit manually
:: Finds node from nvm-windows, volta, or common install paths, then starts
:: the MCP server. Avoids "spawn node ENOENT" in GUI apps like VS Code.

set "NODE_BIN="

:: ── nvm-windows ──────────────────────────────────────────────────────
if defined NVM_HOME (
  for /f "delims=" %%v in ('dir /b /ad "%NVM_HOME%\\v*" 2^>nul ^| sort /r') do (
    if not defined NODE_BIN (
      if exist "%NVM_HOME%\\%%v\\node.exe" set "NODE_BIN=%NVM_HOME%\\%%v\\node.exe"
    )
  )
)

:: ── volta ─────────────────────────────────────────────────────────────
if not defined NODE_BIN (
  if exist "%LOCALAPPDATA%\\Volta\\bin\\node.exe" set "NODE_BIN=%LOCALAPPDATA%\\Volta\\bin\\node.exe"
)

:: ── common install paths ──────────────────────────────────────────────
if not defined NODE_BIN (
  if exist "%ProgramFiles%\\nodejs\\node.exe" set "NODE_BIN=%ProgramFiles%\\nodejs\\node.exe"
)
if not defined NODE_BIN (
  if exist "%LOCALAPPDATA%\\Programs\\nodejs\\node.exe" set "NODE_BIN=%LOCALAPPDATA%\\Programs\\nodejs\\node.exe"
)

:: ── system PATH ───────────────────────────────────────────────────────
if not defined NODE_BIN (
  for /f "delims=" %%i in ('where node 2^>nul') do (
    if not defined NODE_BIN set "NODE_BIN=%%i"
  )
)

if not defined NODE_BIN (
  echo witboost-ai-toolkit: node not found. Install Node.js ^>= 18. 1>&2
  exit /b 1
)

set "SCRIPT_DIR=%~dp0"
"%NODE_BIN%" "%SCRIPT_DIR%dist\\index.cjs" %*
`;

const MCP_JSON = `{
  // macOS / Linux — uses run.sh to find node regardless of version manager.
  // Windows users: change the two lines below to:
  //   "command": "cmd",
  //   "args": ["/c", ".witboost\\\\mcp-server\\\\run.cmd"],
  "servers": {
    "witboost-ai-toolkit": {
      "type": "stdio",
      "command": "sh",
      "args": [".witboost/mcp-server/run.sh"],
      "env": {}
    }
  }
}
`;

export class CopilotGenerator implements HarnessGenerator {
  harnessName = "copilot";

  generate(agents: AgentDefinition[], config: WitboostConfig, outputDir: string): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Generate .witboost/mcp-server/run.sh — Unix node finder
    files.push({
      path: ".witboost/mcp-server/run.sh",
      content: RUN_SH,
      overwrite: true,
    });

    // Generate .witboost/mcp-server/run.cmd — Windows node finder
    files.push({
      path: ".witboost/mcp-server/run.cmd",
      content: RUN_CMD,
      overwrite: true,
    });

    // Generate .vscode/mcp.json (JSONC — supports // comments)
    files.push({
      path: ".vscode/mcp.json",
      content: MCP_JSON,
      overwrite: true,
    });

    // Generate agent files
    for (const agent of agents) {
      const instructions = resolveVariables(agent, config);

      // .github/agents/<name>.agent.md
      files.push({
        path: `.github/agents/${agent.name}.agent.md`,
        content: this.buildAgentMd(agent, instructions),
        overwrite: true,
      });

      // .github/instructions/<name>.instructions.md — on-demand for the default agent
      // Loaded automatically when the agent detects witboost/MCP intent in the chat,
      // without burning tokens on every unrelated conversation.
      files.push({
        path: `.github/instructions/${agent.name}-lifecycle.instructions.md`,
        content: this.buildInstructionsMd(agent, instructions),
        overwrite: true,
      });
    }

    return files;
  }

  /** Replace harness-agnostic confirmation language with vscode_askQuestions for VS Code Copilot */
  private addCopilotConfirmation(instructions: string): string {
    return instructions
      .replace(
        /\*\*explicitly ask the user for confirmation\*\* and wait for an affirmative answer\. \*\*Do NOT call `create_data_product` or `add_component` until the user confirms\.\*\*/g,
        "call `vscode_askQuestions` with a single \"Proceed?\" yes/no question. **Do NOT call `create_data_product` or `add_component` until the user answers affirmatively.**",
      )
      .replace(
        /\*\*explicit user approval\*\*/g,
        "**explicit approval via `vscode_askQuestions`**",
      )
      .replace(
        /ask again for confirmation, and wait for re-approval/g,
        "call `vscode_askQuestions` again, and wait for re-approval",
      );
  }

  private buildAgentMd(agent: AgentDefinition, instructions: string): string {
    const copilotInstructions = this.addCopilotConfirmation(instructions);
    const lines = [
      "---",
      `description: "${agent.description.replace(/\n/g, " ").trim()}"`,
      "tools:",
      '  - "witboost-ai-toolkit"',
      "---",
      "",
      copilotInstructions,
    ];
    return lines.join("\n");
  }

  private buildInstructionsMd(agent: AgentDefinition, instructions: string): string {
    // Collect MCP tool names from all resolved skills for the description
    const toolNames = [...new Set(agent.resolvedSkills.flatMap((s) => s.tools))];
    const toolsList = toolNames.join(", ");
    const descriptionBase = agent.description.replace(/\n/g, " ").trim();
    const description =
      `Use when working with Witboost: ${descriptionBase}. ` +
      `Applies when using Witboost MCP tools (${toolsList}), ` +
      `or when the user mentions data product lifecycle, governance policies, ` +
      `catalog-info, parameters.yaml, witboost scaffolder, output ports, workloads, or storage components.`;

    const lines = [
      "---",
      `description: "${description.replace(/"/g, "'")}"`,
      "---",
      "",
      this.addCopilotConfirmation(instructions),
    ];
    return lines.join("\n");
  }
}
