import type { WitboostConfig } from "../config/schema.js";

/** Overrides for specific harness generators */
export interface HarnessOverrides {
  copilot?: { command?: string; promptFile?: string };
  claude?: { subcommand?: string };
  codex?: { section?: string };
  gemini?: Record<string, never>;
  deepagents?: { model?: string; middleware?: string[]; skills?: boolean };
}

/** Skill definition parsed from SKILL.md YAML frontmatter */
export interface SkillDefinition {
  name: string;
  description: string;
  tools: string[];
  content: string;
}

/** Canonical agent definition parsed from YAML+Markdown */
export interface AgentDefinition {
  name: string;
  displayName: string;
  description: string;
  tools: string[];
  skills: string[];
  resolvedSkills: SkillDefinition[];
  category?: string;
  instructions: string;
  variables?: Record<string, string>;
  harness?: HarnessOverrides;
}

/** A file generated by a harness generator */
export interface GeneratedFile {
  path: string;
  content: string;
  overwrite: boolean;
}

/** Interface for pluggable harness generators */
export interface HarnessGenerator {
  harnessName: string;
  generate(
    agents: AgentDefinition[],
    config: WitboostConfig,
    outputDir: string,
  ): GeneratedFile[];
}
